### ISSUE TITLE
Docs for RDMI

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/rdmi#2]
Hi @ncarboni 

I feel we need to document the project more thoroughly. Would you mind adding all relevant  documentation in the read me or so? 

Thanks, Th.

**Comment by ncarboni** [comment]
Hi @thomashaensli , 
I kept it light with all the necessary input for the reader. If more information is needed I suggest to use the internal wiki of the repository. I close, feel free to reopen
