### ISSUE TITLE
old data in RDS-DEV

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#20]
The data present in RDS-DEV comprises several old datasets with the old prefix that need to be cleaned. Easy to check with :

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT DISTINCT ?concept
WHERE {
    ?concept ?p ?o
    FILTER ( strstarts(str(?concept), "http://grp.swissartresearch.net") )
}
LIMIT 100

```

**Comment by ymark** [comment]
The reason for these data was the existence of some (testing) data found under the namedgraph <http://www.bigdata.com/rdf#nullGraph>

The instances in the namedgraph were "orphan" in the sense that the only information attached to it was the rdfs:label (which in some cases was erroneous as well). 
The namedgraph has been removed.

@ncarboni you are welcome to test.

**Comment by ncarboni** [comment]
@ymark from initial tests seems perfect
! will do further testing, but in the meanwhile I close
