### ISSUE TITLE
X3ML mappings

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#21]
The mapping files present in the [google drive folder](https://drive.google.com/drive/folders/1clcMy8xR3cW25Qbgcw0BuLQrLmfNdQ8Q) are old and do not correspond to the current mappings. 
They need to be updated in order for me to review modelling.

Let's keep the old ones in a folder (e.g. "old mappings") and create a new ones.

edit: create new ones and add them on github

**Comment by ncarboni** [comment]
Linked with issue #11

**Comment by ncarboni** [comment]
edited after 23/01 meeting: to add mapping files on github

**Comment by MinadakisNikos** [comment]
Persons and Groups mappings refined and uploaded here:

https://drive.google.com/drive/folders/1cNWcr9ynD9NDDSQwjtf4EXIVpkaKDsiW

(Will also commit to git)

**Comment by ncarboni** [comment]
Thank. I will check them out and in case open new issues.

**Comment by ncarboni** [comment]
Added them on git. Closing

**Comment by ncarboni** [comment]
Reopen, missing mapping of places?

**Comment by MinadakisNikos** [comment]
Yes persons and groups had been added, persons added today since we refined it this week. Feel free to test :)

**Comment by ncarboni** [comment]
Great! Just to be sure to not start from the wrong side: the Place in the RDS-DEV present now are all generated by the mapping in drive using the file [here](https://workspace.digitale-diathek.net/confluence/display/RDMI/1.+Place) as base for the transformation? @MinadakisNikos @ymark

**Comment by MinadakisNikos** [comment]
It was based on the previous version of it. The new RDFs are  being produced now.

**Comment by ncarboni** [comment]
ok, just made a note about the mapping in issue #35 . Hope in time for uploading them :-)

**Comment by MinadakisNikos** [comment]
Test please

**Comment by ncarboni** [comment]
Everything seems fine here! thanks :-)
