### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#22]
Some information pertaining to persons and groups uploaded to the[files list](https://workspace.digitale-diathek.net/confluence/pages/viewpage.action?pageId=60653625) have not been transformed/added to RDS-DEV. 

Examples:

https://resource.swissartresearch.net/group/C9315B13-EF18-4197-8A96-01C9DC3A8A2E
https://resource.swissartresearch.net/person/495AD572-DB1F-40FC-AD7E-51CF2B63235E

List will be shared

**Comment by MinadakisNikos** [comment]
It is not a bug. We never had transformed and import everything due to the big size, as discussed in previous calls. Will do it this time. Do you think we should close it?

**Comment by ncarboni** [comment]
feel free to close it as soon as you transform/update, so we know where we are at :-)

**Comment by MinadakisNikos** [comment]
Completed. Please test

**Comment by ncarboni** [comment]
Does seems to not everything is fully transferred. The instance:
https://resource.swissartresearch.net/group/C9315B13-EF18-4197-8A96-01C9DC3A8A2E
does not seems to be [there](https://rds-dev.swissartresearch.net/sparql#query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0A%0ASELECT+*+WHERE+%7B%0A%0A+%3Chttps%3A%2F%2Fresource.swissartresearch.net%2Fperson%2FC9315B13-EF18-4197-8A96-01C9DC3A8A2E%3E+%3Fp+%3Fo+.%0A%0A%7D). If it can help, it was present in the file grp-groupsPartA

**Comment by ymark** [comment]
The resource wasn't in the generated XML data (not sure why), so we re-run the XML generation, as well as the transformation to RDF and reloaded the data on the platform.

In addition, we've found some minor issues in the generator policy and the mappings for groups and updated them accordingly.

@ncarboni please check.

**Comment by ncarboni** [comment]
all the group records are there. Need to fix the modelling of some information but I will open another issue. close this one in the meanwhile :-) 
Thanks!
