### ISSUE TITLE
Instances without labels

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#23]
A series of instances are present in the KB without labels (or any relevant information), because they are only recipient (object in <s,p,o>). We should hide those instances from the carousel and search of the KB.

Example of instance are the tgn identifiers.

**Comment by MinadakisNikos** [comment]
Done in the carousel, will be solved in general with the new mappings. Please Test.

**Comment by ncarboni** [comment]
Seems to be resolved. Great, thanks! I will close and reopen if something does not look right
