### ISSUE TITLE
Place in carousel should display appellation as label

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#24]
Places in the carousel do not display the E42 Appellation but the appellation of an identifier (we should also review the mapping).
Example:
Nísoi Aiyaíou, Ellás, Europe, World in the image below 
<img width="1485" alt="carousel" src="https://user-images.githubusercontent.com/5669838/72717265-ff604b00-3b73-11ea-94b9-8b57590b6ab7.png">

is the place identifier used in the the [corresponding record](https://rds-dev.swissartresearch.net/resource/?uri=http%3A%2F%2Fresource.swissartresearch.net%2Fplace%2F1174504B-73F6-4EE4-9AC1-B0FEA25FD35A)
However, the record present an appellation (a more readable one). Better use that one.

**Comment by MinadakisNikos** [comment]
Please Test.

For the cases that are not labels, the issue will be solved after the hiding of these according to issue #23

**Comment by ncarboni** [comment]
should be ok now, thanks !
