### ISSUE TITLE
Home link in the page breadcrumb does not work 

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#25]
when visualising a record, the home link in the page breadcrumb does not work. See image below

<img width="1859" alt="breadcrump" src="https://user-images.githubusercontent.com/5669838/72717714-e015ed80-3b74-11ea-9c24-bd62cb5b0b65.png">

**Comment by MinadakisNikos** [comment]
It has been resolved, please check it and let us close it.

**Comment by ncarboni** [comment]
Hi great, works everywhere except from an instance of  built work(e.g. [example](https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fwork%2F0009C105-F7BF-4860-A95E-5B790A0F545C)  ). But probably @matteoLorenzini has control over it
