### ISSUE TITLE
Setup new VM

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/rdmi#30]
Host: sari2.ethz.ch

News to be added

**Comment by ncarboni** [comment]
linked with issue #28

**Comment by thomashaensli** [comment]
Development VM
- sari1.ethz.ch

Productive VM: 
- sari2.ethz.ch (online since 1/28)

See https://workspace.digitale-diathek.net/confluence/x/BITmAw for distribution of instances to
