### ISSUE TITLE
Builtwork icon

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#31]
To change the icon for builtwork

**Comment by ymark** [comment]
Changed the icon that is shown in the carousel with the one shown for each instance.
@ncarboni  If you have any thoughts about an alternative icon feel free to propose.

**Comment by ncarboni** [comment]
@ymark great! i had sent one to @matteoLorenzini, he will probably change it in the near future. in the meanwhile, let’s close here
