### ISSUE TITLE
Mapping Identifier Source

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#33]
I would eliminate this part (for each id: wikidata, ulan etc.) unless it breaks something. It appears to me that it does not add any information. It was specifically thought for historical sources of a name/id, but in this case it does not fulfil the purpose.

https://github.com/swiss-art-research-net/rdmi/blob/bdb268091767ea36485fad6ba37f4cdb4dfae3dd/3M_Mapping/Reference_data_model_mapping/smartup/mappings-Person.x3ml#L794

Moreover, it creates duplicates in the identifier section of the instances (e.g. [here](https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fperson%2FFB8A59A2-5B6D-459F-98F0-3E5736BB8AB5) )

Do you think it will break something, it is doable for the LODLAM milestone

**Comment by ymark** [comment]
No, it does not break anything so it can be safely removed.
The rationale for having it there is that it provides a resolvable URL to other sources (i.e. GND, wikidata, etc.) that shows more information about the entity of interest (the corresponding person in this case) in a human-readable html page (the more from... tabs show some of these information).

@ncarboni  the choice is yous :-)

**Comment by ncarboni** [comment]
@ymark can we not build it up from the E42 identifier for it? in case it requires some time we can easily move it to MVP1, my major concern now (lodlam) is to not show the two ids next to each other in the section. maybe we can quickly use this fix? what do you think?

**Comment by ymark** [comment]
We can always built it up from the E42, however in this case the information will only be visible from the corresponding templates, (you can find it by browsing the KB through SPARQL). 

We can either remove it from the mappings and as evident it won't be shown, or we can simply remove the corresponding fields from the template.

**Comment by ncarboni** [comment]
Ok, so it is not anymore a mapping problem, but just a visualisation problem. I close here and open a new issue
