### ISSUE TITLE
WKT 

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#35]
This does not produce WKT really. The structure should be expressed according to the format
> POINT(lat long)
example:
> POINT(7.029336 46.287932)

I do presume we do need one link just having 4 value:
constant "POINT("
xpath  plSubstance_tgn_lat
xpath plSubstance_tgn_long
constant ")"

https://github.com/swiss-art-research-net/rdmi/blob/92add6fb2f43e29e4d9ed49dc2ebcb12b1502459/3M_Mapping/Reference_data_model_mapping/smartup/mappings-Place.x3ml#L167-L208

**Comment by ncarboni** [comment]
done

**Comment by ncarboni** [comment]
Reopened. The instance generator currently produce xsd:string. This is due to the mapping use of Literak as instance generator
```xml
 <type>geo:wkt</type> 
                  	<instance_generator name="Literal"> 
```
The generator TypedLiteralGen should be used.
Current data in knowledge base should also be updated

**Comment by ymark** [comment]
The mappings/generators have been updated

```
<entity>
	<type>geo:wkt</type>
	<instance_generator name="typedLiteralGen">
		<arg name="text" type-"xpath">concat("POINT({",text(),"} {",../plSubstance_tgn_long/text(),"})")</arg>
	</instance_generator>
</entity>
```

**Comment by MinadakisNikos** [comment]
To be tested

**Comment by ncarboni** [comment]
no graph is necessary and the type should be geo:wktLiteral
Tried to adjust it:
```xml
<entity>
	<type>geo:wktLiteral</type>
	<instance_generator name="typedLiteralGen">
		<arg name="text" type-"xpath">concat("POINT(",text()," ",../plSubstance_tgn_long/text(),")")</arg>
	</instance_generator>
</entity>
```

**Comment by ymark** [comment]
Updated the mapping accordingly, re-transformed and re-uploaded the data.
@ncarboni  please check.

**Comment by ncarboni** [comment]
Perfect! 
Data need to be updated, but mapping is great. I am closing it
