### ISSUE TITLE
Map component for Places

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#36]
Adding a map component in the Places template

documentation:
https://wikidata.metaphacts.com/resource/Help:SemanticMap

To be further discussed after February

**Comment by ncarboni** [comment]
To be removed from Place

**Comment by MinadakisNikos** [comment]
Should we remove it or just there for the video, and not click on it?

**Comment by ncarboni** [comment]
better remove it for now :-)

**Comment by ymark** [comment]
instead of removing it, I hid it (added within html comments)

**Comment by ncarboni** [comment]
even better, we are gonna reuse it later :-)
Thanks!
