### ISSUE TITLE
Migrate v2.x instances to v3.3

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/rdmi#46]
Hi Nikos, 
here's the list/priority to migrate our v2.x instances to v3.3 for now: 

- http://rds-dev.swissartresearch.net/ -> https://rds.swissartresearch.net/
- http://grp.swissartresearch.net/ -> https://grp-v3.swissartresearch.net/
- https://fw.swissartresearch.net/ -> https://fw-v3.swissartresearch.net/
- new -> http://ed.swissartresearch.net/

All these are going to live on sari2.ethz.ch. Details see: https://workspace.digitale-diathek.net/confluence/x/BITmAw

Would be great to have by the end of this week (i.e. 2/7/2020)

**Comment by MinadakisNikos** [comment]
Hey Thomas,

will do it right after your demo/video to be sure nothing will be broken. Just let us know when you are done so we can start the process.

**Comment by ncarboni** [comment]
Don't know if thomas will see this. But he probably will have another presentation on Friday. How much time do you need for migrating the instances? Probably better to do it next week

**Comment by ymark** [comment]
It's not actually the time that is needed to do the migration. 
We would like to avoid strange circumstances and problems since this is a migration between different major versions (from 2.x to 3.3)

**Comment by MinadakisNikos** [comment]
We are waiting for root access on sari2 VM. (already informed @thomashaensli through email)

**Comment by ncarboni** [comment]
I think we can close this
