### ISSUE TITLE
upload XML data

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#47]
@MinadakisNikos @ymark would you mind uploading the XML used for the transformation (we need them as target for providing the new data) [on the same google folder](https://drive.google.com/drive/folders/1cNWcr9ynD9NDDSQwjtf4EXIVpkaKDsiW) we do use for the x3ml (or same space)

**Comment by ymark** [comment]
Done. Uploaded in folder [Input XML](https://drive.google.com/drive/folders/1RiC2krbsnVr6Iyk76t_xFWld-jvl-5_1)

**Comment by ncarboni** [comment]
great! Thanks
