### ISSUE TITLE
Missing icons on landing page

### ISSUE THREAD

**Issue by matteoLorenzini** [swiss-art-research-net/rdmi#48]
On the landing page the top left icon and the bottom left icon are missing

**Comment by ymark** [comment]
The headers and footers were updated by @thomashaensli a few days ago (check #29).
It seems that that the paths for the corresponding logos were not added.

We can fix it as well. @thomashaensli let us know if you have any logos we can use for this.

**Comment by ncarboni** [comment]
<img width="528" alt="sari" src="https://user-images.githubusercontent.com/5669838/75326597-914e2880-5883-11ea-90bd-de941f096e4b.png">

This is the logo :-)
Thanks!

**Comment by ymark** [comment]
Done. Please check

**Comment by ncarboni** [comment]
Great, would you mind adding it also in the footer?

**Comment by ymark** [comment]
Ah, I didn't notice that. Done
