### ISSUE TITLE
data transformation for person not language aware

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/rdmi#5]
Hi Nikos. 

just checked on the latest data (as of now). I see that the appellation and description (short) are displayed in all four languages though they are the same. Can we do something about it? 

See https://rds-dev.swissartresearch.net/resource/?uri=http%3A%2F%2Fgrp.swissartresearch.net%2Fperson%2F49BC8316-FB50-43B3-92BB-09245221E2CC

**Comment by MinadakisNikos** [comment]
Hi Thomas, I mentioned in our call that I did this on purpose to test the visualization compinations (since there is only one language value for this record). It will not be there after the refinement.

**Comment by ncarboni** [comment]
Still on, I will add to the "LODLAM todo" milestone

**Comment by MinadakisNikos** [comment]
Test it. Solved.

**Comment by ncarboni** [comment]
@MinadakisNikos seems to appear in the instance of Places. For [example](https://rds-dev.swissartresearch.net/resource/?uri=http%3A%2F%2Fresource.swissartresearch.net%2Fplace%2FF49B2EDD-4D0A-4E02-839A-AE09CB876820).

**Comment by MinadakisNikos** [comment]
Ok the ticket was only for persons so I did not look at places. It is
solved now

**Comment by ncarboni** [comment]
Last (sorry, noticed now). Also the parent place (P89) for places have the same issue. Example [here](https://rds-dev.swissartresearch.net/resource/?uri=http%3A%2F%2Fresource.swissartresearch.net%2Fplace%2F4793FC72-5C5E-4968-9A93-F9ADF7162B14)

**Comment by MinadakisNikos** [comment]
Its not the same issue. This is another phenomenon because germany has two
URIs one with the UUID coming from you and another one with the tgn id.
Maybe we should keep only one of these as a direct link.

**Comment by ncarboni** [comment]
To review mappings @ncarboni

**Comment by ncarboni** [comment]
Two identified problem in the call of 31 Jan 2020:

* biography in person instance presents different languages even though it is the same. Example [here](https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fperson%2F75A72225-E0DE-4053-A512-02473AA1ED71)
* Place name should present values from: 
   + plIdentifier_nameGeneric  
   + plIdentifier_nameEn	
   + plIdentifier_nameDe	
   + plIdentifier_nameFr	
   + plIdentifier_nameIT


@MinadakisNikos @ymark

**Comment by MinadakisNikos** [comment]
Fixed. Test please

**Comment by ncarboni** [comment]
great 👍
