### ISSUE TITLE
Both Group and Actor

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#51]
The record 
https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fgroup%2F3E1F990A-2368-4B81-9B05-10675779E790

is both a Group and Actor

**Comment by ncarboni** [comment]
No others are both group and actors

**Comment by ncarboni** [comment]
It is SARI. Should be a Group (corporate body) P2  http://vocab.getty.edu/aat/300386361

**Comment by MinadakisNikos** [comment]
This happens because from the persons mapping SARI is an identifier provider.

The attribute assignment has range Actor.

This is why it has two types which is not an issue from our point of view since every Group is a subclass of Actor. TBD

**Comment by ncarboni** [comment]
Checking the data I think that the issue comes from the fact that <https://resource.swissartresearch.net/group/3E1F990A-2368-4B81-9B05-10675779E790> is both an identifier provider and listed as _01_actor_nameclass_identifier_identifierUUID, therefore result also a E39 for the range of E15 in the mapping of the local identifier:

https://github.com/swiss-art-research-net/rdmi/blob/48d1a067565f33366a4283f2d750c9223d337736/3M_Mapping/Reference_data_model_mapping/smartup/mappings-Group.x3ml#L45-L100

Problem is in the data and should be changed from our side with the new set of data. 
in the meanwhile maybe we can ignore it adding 


```xml
 		<if>
                    <not>
                        <if>
                            <equals value="3E1F990A-2368-4B81-9B05-10675779E790">text()</equals>
                        </if>
                    </not>
                </if>
```

to the mapping above?

**Comment by ncarboni** [comment]
just quickly added in the mapping and update them in https://github.com/swiss-art-research-net/rdmi/tree/master/3M_Mapping/Reference_data_model_mapping/smartup
