### ISSUE TITLE
Group type

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#52]
The type assigned to a group ( the two choice are group or corporate body in the original file) should be:

Corporate body: http://vocab.getty.edu/aat/300386361
Group: http://vocab.getty.edu/aat/300025948

Ex:

```ttl
<sari/123/group> a crm:E74_Group ;
  crm:P2_has_type <http://vocab.getty.edu/aat/300386361>
```

**Comment by ncarboni** [comment]
p.s. @ymark after the changes and issue I assigned today do not waste time re-uploading the data. I have a couple of other issues I need to properly document!

**Comment by MinadakisNikos** [comment]
Done Please Check

**Comment by ncarboni** [comment]
Seems fine by me!

**Comment by ncarboni** [comment]
tested. thanks!
