### ISSUE TITLE
Missing Nationalities in the modelling of groups

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#55]
The nationalities for the group uploaded here https://workspace.digitale-diathek.net/confluence/pages/viewpage.action?pageId=60653625 (grp-groupsPartA_nationalities.xlsx) has not been modelled.

The modelling should be:

E74 → P107i → E74 -> P2 

Ex:

```ttl
<https://resource.swissartresearch.net/group/10D37321-9EC6-4452-A3DB-D8103F6D6A5E> a crm:E74_Group ;
crm:is_current_or_former_member_of <https://resource.swissartresearch.net/group/8E635BEB-717C-41BE-A00F-7A0ACA33D506> .

<https://resource.swissartresearch.net/group/8E635BEB-717C-41BE-A00F-7A0ACA33D506> a crm:E74_Group ;
	crm:P2_has_type <https://resources.swissartresearch.net/vocab/nationalities/8E635BEB-717C-41BE-A00F-7A0ACA33D506> ;
	crm:P2_has_type <http://vocab.getty.edu/aat/300128207> .

```

So we use the UUID of the  _01_actor_nameclass_identifierUUID identify the group (present in the KB), while the value of _03_actor_social_nationalAffiliationUUID is used for :
+ the second group (identifying the nation)
+ the type which identify the entry in our nationalities vocabulary (present in the KB).

**Comment by MinadakisNikos** [comment]
Done. Please test

**Comment by ncarboni** [comment]
Added the property number to the mapping, eliminated the gender type (?), took out the uri constant and add link it to the id of the nationalities. New mapping in https://github.com/swiss-art-research-net/rdmi/tree/master/3M_Mapping/Reference_data_model_mapping/smartup @MinadakisNikos
