### ISSUE TITLE
Template for death and birth not working

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#57]
The templates for death and birth do not seems to work.

Ex:

https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fperson%2F68BB1C99-3C70-4873-BF46-912138444268%2Fdeath

https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fperson%2F68BB1C99-3C70-4873-BF46-912138444268%2Fbirth

**Comment by MinadakisNikos** [comment]
These templates are not working because they have been altered by someone (not from SmartUp). Did you copy these templates from another system?

**Comment by ncarboni** [comment]
It is the first time I even click on them :-) Maybe they have been copied before.
@matteoLorenzini are you tweaking them maybe?

I'òll leave it open for discussion and propositions on how to fix it

**Comment by MinadakisNikos** [comment]
Copy a paste another template that works

**Comment by ncarboni** [comment]
Do not how to replicate the error. Closing in the meanwhile
