### ISSUE TITLE
Group template

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#62]
The template for group needs to be done in order to look similar to the one of person. Currently it looks like 

https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fgroup%2F004C3D1B-C4FF-4898-A925-008932E12660

**Comment by ymark** [comment]
Created first draft of the template for groups

**Comment by ncarboni** [comment]
Template was fine. To be added to the carousel and close

**Comment by ncarboni** [comment]
done, I close
