### ISSUE TITLE
Εxternal identifiers with non-resolvable URLs

### ISSUE THREAD

**Issue by ymark** [swiss-art-research-net/rdmi#64]
This happens because the generator policy used should be updated. 
For example the Wikidata URL for https://resource.swissartresearch.net/group/004C3D1B-C4FF-4898-A925-008932E12660 is https://www.wikidata.org/wiki/https%3A//www.wikidata.org/wiki/Q463303 instrad of https://www.wikidata.org/wiki/Q463303

For sure, this appears on Groups. To check if it occurs in other entities as well.

**Comment by MinadakisNikos** [comment]
Done. Please Test
