### ISSUE TITLE
Redesign: new instance button/link

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#66]
Currently it is possible to add new instances only by navigating to an existing one.
A button or link should be created in the top navigation bar in order to be accessible from everywhere. 
Problem to foresee: 

+ a modal window to choose entity
+ properties to be shown in the "new user navigation window".

linked with issue #40

**Comment by thomashaensli** [comment]
same here: we can limit the authoring tab to users with SPARQL UPDATE priviledges

**Comment by ncarboni** [comment]
If I remember correctly, it has been decided to have an option in the menubar. To be discussed

**Comment by ncarboni** [comment]
to be added in the header under workspace

**Comment by ymark** [comment]
Links pointing to Data Input forms have been added on menu bar under Workspace.
They're available only for authorized users.

**Comment by ncarboni** [comment]
great! thanks :-)
