### ISSUE TITLE
Redesign and permission: who can see authoring form

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#67]
Currently not logged user can see the authoring form for each instance. Would be possible to restrict the view to only the users who have the right to do so (the one with SPARQL INSERT)? 

Example [here](https://rds-dev.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fperson%2FFB8A59A2-5B6D-459F-98F0-3E5736BB8AB5)

**Comment by thomashaensli** [comment]
Limit to users that have SPARQL Update rights. See http://grp.swissartresearch.net for the machanism.

**Comment by ncarboni** [comment]
this has been fixed
