### ISSUE TITLE
Adding authoring form for place

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/rdmi#7]
To add the authoring form for inserting new entries for places according to the field marked in the [authoring form]( https://docs.google.com/spreadsheets/d/1CnSej6X_-sQXCIHk43SPAHHB527C1nwrC7WGyGlBfbI/edit#gid=1164848979)

**Comment by MinadakisNikos** [comment]
This is alrady there. We just have to add it to the langing page maybe. https://rds-dev.swissartresearch.net/resource/?uri=http%3A%2F%2Fgrp.swissartresearch.net%2Fplace%2F03E83C70-EA76-4832-80F3-7C111AB84904

**Comment by ncarboni** [comment]
true
