### ISSUE TITLE
admin accounts

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/rdmi#9]
Hi @MinadakisNikos and @matteoLorenzini 

as of now, everyone is working as user 'admin'. We should have personalized accounts, at least  for you two guys (for editing fields etc.) 

Can you please set up a personalized with full admin rights for yourself?

**Comment by MinadakisNikos** [comment]
Ok done, my username is nikos and yannis' is yannis :)

**Comment by matteoLorenzini** [comment]
Ok, I have created mine.. I think we can consider this issue as solved.
